# This will appear before many messages from the plugin.
message-prefix: '&7[&bChatGame&7]'

# Use a minecraft colour code here to pick the message colour
message-colour: 'a'

# The highlight colour (to complement the above colour)
highlight-colour: 'b'

# Errors will be this colour.
error-colour: 'c'

# Error highlights
error-highlight: '7'

settings:
  # Whether or not to require /guess (/g) for players to guess. Enable this to reduce spam.
  require-guess-command: false

  # The number of seconds between the end of one round and the start of the next.
  seconds-between-rounds: 180

  # Should players be listening to the game by default?
  listen-by-default: true

  # On which day should weekly stats be reset?
  reset-day: 'SUNDAY'

  # At what time should resets occur?
  reset-time: '12:00'

  # Optionally, you can add a language file from
  # your minecraft client ([version].jar\assets\minecraft\lang\[language].json),
  # and words generated will pull from that json language file.
  #
  # Doing this ensures that words are shown correctly (i.e. "Jack o'Lantern instead of
  # "Jack O Lantern" or "Bucket of Pufferfish" instead of "Pufferfish Bucket")
  #
  # The plugin doesn't include the English lang file by default,
  # so you'll need to retrieve it from your client jar yourself.
  minecraft-lang: 'lang/en_us.json'

  # Choose how frequently a given category comes up.
  # To disable a game, set the percentage to 0.
  rates:
    unscramble: 20
    math: 20
    trivia: 20
    quicktype: 20
    reveal: 20